package sy.model;

public class Fav {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fav.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fav.productid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fav.memberid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String memberid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fav.id
     *
     * @return the value of fav.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fav.id
     *
     * @param id the value for fav.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fav.productid
     *
     * @return the value of fav.productid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fav.productid
     *
     * @param productid the value for fav.productid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fav.memberid
     *
     * @return the value of fav.memberid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fav.memberid
     *
     * @param memberid the value for fav.memberid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setMemberid(String memberid) {
        this.memberid = memberid == null ? null : memberid.trim();
    }
}