package sy.model;

public class Imgadv {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgadv.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgadv.imgurl
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgadv.type
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgadv.id
     *
     * @return the value of imgadv.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgadv.id
     *
     * @param id the value for imgadv.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgadv.imgurl
     *
     * @return the value of imgadv.imgurl
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgadv.imgurl
     *
     * @param imgurl the value for imgadv.imgurl
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgadv.type
     *
     * @return the value of imgadv.type
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgadv.type
     *
     * @param type the value for imgadv.type
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}