package sy.model;

public class Kcrecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kcrecord.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kcrecord.productid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kcrecord.num
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kcrecord.type
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kcrecord.savetime
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String savetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kcrecord.id
     *
     * @return the value of kcrecord.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kcrecord.id
     *
     * @param id the value for kcrecord.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kcrecord.productid
     *
     * @return the value of kcrecord.productid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kcrecord.productid
     *
     * @param productid the value for kcrecord.productid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kcrecord.num
     *
     * @return the value of kcrecord.num
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kcrecord.num
     *
     * @param num the value for kcrecord.num
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kcrecord.type
     *
     * @return the value of kcrecord.type
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kcrecord.type
     *
     * @param type the value for kcrecord.type
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kcrecord.savetime
     *
     * @return the value of kcrecord.savetime
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getSavetime() {
        return savetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kcrecord.savetime
     *
     * @param savetime the value for kcrecord.savetime
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setSavetime(String savetime) {
        this.savetime = savetime == null ? null : savetime.trim();
    }
}