package sy.model;

public class Msg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.content
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.reply
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String reply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.savetime
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String savetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.memberid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String memberid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.id
     *
     * @return the value of msg.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.id
     *
     * @param id the value for msg.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.content
     *
     * @return the value of msg.content
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.content
     *
     * @param content the value for msg.content
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.reply
     *
     * @return the value of msg.reply
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.reply
     *
     * @param reply the value for msg.reply
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.savetime
     *
     * @return the value of msg.savetime
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getSavetime() {
        return savetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.savetime
     *
     * @param savetime the value for msg.savetime
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setSavetime(String savetime) {
        this.savetime = savetime == null ? null : savetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.memberid
     *
     * @return the value of msg.memberid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.memberid
     *
     * @param memberid the value for msg.memberid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setMemberid(String memberid) {
        this.memberid = memberid == null ? null : memberid.trim();
    }
}