package sy.model;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.proinfo
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String proinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.memberid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.price
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.savetime
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String savetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.fkstatus
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String fkstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.fhstatus
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String fhstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.tel
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.addr
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.type
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderid
     *
     * @return the value of order.orderid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderid
     *
     * @param orderid the value for order.orderid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.proinfo
     *
     * @return the value of order.proinfo
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getProinfo() {
        return proinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.proinfo
     *
     * @param proinfo the value for order.proinfo
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setProinfo(String proinfo) {
        this.proinfo = proinfo == null ? null : proinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.memberid
     *
     * @return the value of order.memberid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.memberid
     *
     * @param memberid the value for order.memberid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setMemberid(String memberid) {
        this.memberid = memberid == null ? null : memberid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.price
     *
     * @return the value of order.price
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.price
     *
     * @param price the value for order.price
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.savetime
     *
     * @return the value of order.savetime
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getSavetime() {
        return savetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.savetime
     *
     * @param savetime the value for order.savetime
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setSavetime(String savetime) {
        this.savetime = savetime == null ? null : savetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.fkstatus
     *
     * @return the value of order.fkstatus
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getFkstatus() {
        return fkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.fkstatus
     *
     * @param fkstatus the value for order.fkstatus
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setFkstatus(String fkstatus) {
        this.fkstatus = fkstatus == null ? null : fkstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.fhstatus
     *
     * @return the value of order.fhstatus
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getFhstatus() {
        return fhstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.fhstatus
     *
     * @param fhstatus the value for order.fhstatus
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setFhstatus(String fhstatus) {
        this.fhstatus = fhstatus == null ? null : fhstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.tel
     *
     * @return the value of order.tel
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.tel
     *
     * @param tel the value for order.tel
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.addr
     *
     * @return the value of order.addr
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.addr
     *
     * @param addr the value for order.addr
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.type
     *
     * @return the value of order.type
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.type
     *
     * @param type the value for order.type
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}