package sy.model;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.proname
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String proname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prono
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String prono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.img
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.field1
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String field1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.field2
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String field2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.field3
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String field3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.field4
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String field4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.field5
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String field5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.field6
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String field6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.field7
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String field7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.field8
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String field8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.field9
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String field9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.field10
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String field10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.protype
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String protype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.delstatus
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String delstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.remark
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.proname
     *
     * @return the value of product.proname
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getProname() {
        return proname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.proname
     *
     * @param proname the value for product.proname
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setProname(String proname) {
        this.proname = proname == null ? null : proname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prono
     *
     * @return the value of product.prono
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getProno() {
        return prono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prono
     *
     * @param prono the value for product.prono
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setProno(String prono) {
        this.prono = prono == null ? null : prono.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.img
     *
     * @return the value of product.img
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.img
     *
     * @param img the value for product.img
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.field1
     *
     * @return the value of product.field1
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.field1
     *
     * @param field1 the value for product.field1
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.field2
     *
     * @return the value of product.field2
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.field2
     *
     * @param field2 the value for product.field2
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setField2(String field2) {
        this.field2 = field2 == null ? null : field2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.field3
     *
     * @return the value of product.field3
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.field3
     *
     * @param field3 the value for product.field3
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setField3(String field3) {
        this.field3 = field3 == null ? null : field3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.field4
     *
     * @return the value of product.field4
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getField4() {
        return field4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.field4
     *
     * @param field4 the value for product.field4
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setField4(String field4) {
        this.field4 = field4 == null ? null : field4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.field5
     *
     * @return the value of product.field5
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getField5() {
        return field5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.field5
     *
     * @param field5 the value for product.field5
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setField5(String field5) {
        this.field5 = field5 == null ? null : field5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.field6
     *
     * @return the value of product.field6
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getField6() {
        return field6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.field6
     *
     * @param field6 the value for product.field6
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setField6(String field6) {
        this.field6 = field6 == null ? null : field6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.field7
     *
     * @return the value of product.field7
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getField7() {
        return field7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.field7
     *
     * @param field7 the value for product.field7
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setField7(String field7) {
        this.field7 = field7 == null ? null : field7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.field8
     *
     * @return the value of product.field8
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getField8() {
        return field8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.field8
     *
     * @param field8 the value for product.field8
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setField8(String field8) {
        this.field8 = field8 == null ? null : field8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.field9
     *
     * @return the value of product.field9
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getField9() {
        return field9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.field9
     *
     * @param field9 the value for product.field9
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setField9(String field9) {
        this.field9 = field9 == null ? null : field9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.field10
     *
     * @return the value of product.field10
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getField10() {
        return field10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.field10
     *
     * @param field10 the value for product.field10
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setField10(String field10) {
        this.field10 = field10 == null ? null : field10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.protype
     *
     * @return the value of product.protype
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getProtype() {
        return protype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.protype
     *
     * @param protype the value for product.protype
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setProtype(String protype) {
        this.protype = protype == null ? null : protype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.delstatus
     *
     * @return the value of product.delstatus
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.delstatus
     *
     * @param delstatus the value for product.delstatus
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setDelstatus(String delstatus) {
        this.delstatus = delstatus == null ? null : delstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.remark
     *
     * @return the value of product.remark
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.remark
     *
     * @param remark the value for product.remark
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}