package sy.model;

public class Protype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column protype.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column protype.typename
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column protype.delstatus
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String delstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column protype.id
     *
     * @return the value of protype.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column protype.id
     *
     * @param id the value for protype.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column protype.typename
     *
     * @return the value of protype.typename
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column protype.typename
     *
     * @param typename the value for protype.typename
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column protype.delstatus
     *
     * @return the value of protype.delstatus
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column protype.delstatus
     *
     * @param delstatus the value for protype.delstatus
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setDelstatus(String delstatus) {
        this.delstatus = delstatus == null ? null : delstatus.trim();
    }
}