package sy.model;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.r_id
     *
     * @mbggenerated Thu Mar 31 23:46:38 CST 2016
     */
    private Integer rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rolltype
     *
     * @mbggenerated Thu Mar 31 23:46:38 CST 2016
     */
    private String rolltype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.r_id
     *
     * @return the value of role.r_id
     *
     * @mbggenerated Thu Mar 31 23:46:38 CST 2016
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.r_id
     *
     * @param rId the value for role.r_id
     *
     * @mbggenerated Thu Mar 31 23:46:38 CST 2016
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rolltype
     *
     * @return the value of role.rolltype
     *
     * @mbggenerated Thu Mar 31 23:46:38 CST 2016
     */
    public String getRolltype() {
        return rolltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rolltype
     *
     * @param rolltype the value for role.rolltype
     *
     * @mbggenerated Thu Mar 31 23:46:38 CST 2016
     */
    public void setRolltype(String rolltype) {
        this.rolltype = rolltype == null ? null : rolltype.trim();
    }
}