package sy.model;

public class Sales {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.productid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.num
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.savetime
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    private String savetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.id
     *
     * @return the value of sales.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.id
     *
     * @param id the value for sales.id
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.productid
     *
     * @return the value of sales.productid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.productid
     *
     * @param productid the value for sales.productid
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.num
     *
     * @return the value of sales.num
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.num
     *
     * @param num the value for sales.num
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.savetime
     *
     * @return the value of sales.savetime
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public String getSavetime() {
        return savetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.savetime
     *
     * @param savetime the value for sales.savetime
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    public void setSavetime(String savetime) {
        this.savetime = savetime == null ? null : savetime.trim();
    }
}