package sy.model;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.ur_id
     *
     * @mbggenerated Fri Apr 01 00:29:22 CST 2016
     */
    private Integer urId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.ur_id
     *
     * @return the value of userrole.ur_id
     *
     * @mbggenerated Fri Apr 01 00:29:22 CST 2016
     */
    public Integer getUrId() {
        return urId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.ur_id
     *
     * @param urId the value for userrole.ur_id
     *
     * @mbggenerated Fri Apr 01 00:29:22 CST 2016
     */
    public void setUrId(Integer urId) {
        this.urId = urId;
    }
}