package sy.dao;

import sy.model.Fav;

public interface FavMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fav
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fav
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int insert(Fav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fav
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int insertSelective(Fav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fav
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    Fav selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fav
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int updateByPrimaryKeySelective(Fav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fav
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int updateByPrimaryKey(Fav record);
}