package sy.dao;

import sy.model.Imgadv;

public interface ImgadvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgadv
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgadv
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int insert(Imgadv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgadv
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int insertSelective(Imgadv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgadv
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    Imgadv selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgadv
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int updateByPrimaryKeySelective(Imgadv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgadv
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int updateByPrimaryKey(Imgadv record);
}