package sy.dao;

import sy.model.Kcrecord;

public interface KcrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kcrecord
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kcrecord
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int insert(Kcrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kcrecord
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int insertSelective(Kcrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kcrecord
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    Kcrecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kcrecord
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int updateByPrimaryKeySelective(Kcrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kcrecord
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int updateByPrimaryKey(Kcrecord record);
}