package sy.dao;

import sy.model.Protype;

public interface ProtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table protype
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table protype
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int insert(Protype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table protype
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int insertSelective(Protype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table protype
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    Protype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table protype
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int updateByPrimaryKeySelective(Protype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table protype
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int updateByPrimaryKey(Protype record);
}