package sy.dao;

import sy.model.Sales;

public interface SalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int insert(Sales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int insertSelective(Sales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    Sales selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int updateByPrimaryKeySelective(Sales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbggenerated Wed Mar 30 09:24:21 CST 2016
     */
    int updateByPrimaryKey(Sales record);
}