package sy.dao;

import sy.model.UserRole;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated Fri Apr 01 00:29:22 CST 2016
     */
    int deleteByPrimaryKey(Integer urId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated Fri Apr 01 00:29:22 CST 2016
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated Fri Apr 01 00:29:22 CST 2016
     */
    int insertSelective(UserRole record);
}